### ISSUE TITLE
iteration in tables does not work

### ISSUE THREAD

**Issue by mhaupt** [medusa-ui/medusa#151]
# What happens?

Using a construct like the following ...

```
<table><tbody>
  <m:foreach collection="col" eachName="itm">
    <tr>
      <td><m:text item="itm.name"/></td>
      <td><m:text item="itm.value"/></td>
    </tr>
  </m:foreach>
</tbody></table>
```

... the table will simply be rendered as "false false" regardless of whether the collection contains more than one element. (Also, "false" is not what's stored, just to make sure.)

Removing the `<table><tbody> ... </tbody></table>` wrapper makes it work as expected, however now we're not generating a table.

# What should happen?

The table should be generated with the iteration creating the appropriate number of table rows with the elements as indicated.

# Some analysis

I believe the root cause to be an issue in the `Jsoup` parser that generates a `Document` from the document's HTML contents after removing the comments (this is in `HTMLCache.getHTMLOrAdd()`).

The HTML source from above _without_ the table/body wrappers will show up correctly in the `Document`.

However, the HTML source _including_ the wrapper will show up like this:

```
<m:foreach collection="col" eachname="itm"> 
  </m:foreach>
  <table>
   <tbody> 
    <tr> 
     <td>
      <m:text item="itm.name" /></td> 
     <td>
      <m:text item="itm.value" /></td> 
    </tr>  
   </tbody>
  </table> 
```

Note how the entire `<m:foreach ...>` part got moved to _before_ the table.

# Now what?

Is this an issue in `Jsoup`, as I suspected? Or is it something else?

**Comment by mhaupt** [comment]
Using the XML parser instead of the HTML parser helps (superficially) here's how `HTMLCache.removeAllCommentsFromHTML()` should look:

    private Document removeAllCommentsFromHTML(String html) {
        return Jsoup.parse(html.replaceAll("(?s)", ""), "", Parser.xmlParser());
    }

While `medusa-ui` compiles and tests just fine with this singular change, there may be additional repercussions; I'll have a go at all of it and use the XML parser everywhere to see if it breaks any of the existing tests.

**Comment by dirkdeyne** [comment]
By using the xmlParser instead of the htmlParser, the initial loading of a page (containing a table) works.

But it goes wrong after updating the table data via DOMChanges.

Created [bug/iteration-table](https://github.com/medusa-ui/medusa/tree/bug/iteration-table) to further investigation.

Refs:
- [table iteration page](medusa-sample-implementation/src/main/resources/pages/integration-tests/bug/table-iteration.html)
- [eventhandler](medusa-sample-implementation/src/main/java/com/sample/medusa/eventhandler/integrationtests/bug/TableIterationEventHandler.java)
- [http://localhost:8080/test/bug/table?load=false](http://localhost:8080/test/bug/table?load=true)

**Comment by kevindeyne** [comment]
So I think it goes wrong because of the contents of the <template> tag.

So, if I ask for the page source, it looks correct (specifically, the template > div > tr > td chain is intact):
```
<thead>
	<tr><th>English</th><th>Dutch</th></tr>
</thead>
<tbody>
	<template m-id="t-1656712348">
		<div m-each="nmb" template-id="t-1656712348">
			<tr>
				<td class="table-item-name"><span from-value="nmb.name">nmb.name</span></td>
				<td class="table-item-value"><span from-value="nmb.value">nmb.value</span></td>
			</tr>
		</div>
	</template>
	<div m-each="nmb" template-id="t-1656712348" index="0">
		<tr>
			<td class="table-item-name"><span from-value="nmb.name">zero</span></td>
			<td class="table-item-value"><span from-value="nmb.value">nul</span></td>
		</tr>
	</div>
...
```

Once rendered in my browser through (Chromium, Firefox) it seems like the contents of the <template> tag are cleaned and look like this:
```
<template m-id="t-1656712348"><div m-each="nmb" template-id="t-1656712348">
                    
                        <span from-value="nmb.name">nmb.name</span>
                        <span from-value="nmb.value">nmb.value</span>
                    
                </div></template>
```

And so subsequent JS is all based on a template missing the tr/td chain.

That's not exactly what I expected. I always figured storing these kinds of half-written fragments is exactly what a <template> tag is for, even if it's invalid or custom tags. I guess that's not the case, but I haven't been able to find any definitive docs yet on that kind of behavior.

**Comment by kevindeyne** [comment]
In case we wish to proceed with the encoding idea, I made an additional branch: [bug/iteration-table-w-encoding](https://github.com/medusa-ui/medusa/tree/bug/iteration-table-w-encoding)

Still unfinished, however. The basic encoding/decoding works, but it doesn't seem to replace values and the table looks weird. Getting too late for me to really continue with a clear mind, but feel free to pick up from there or I can get to it later.

**Comment by kevindeyne** [comment]
Some further research makes it seem like, specifically for tables, the construction of table>div>tr is invalid HTML.

We could potentially use a `<tbody>` to wrap `<tr>` tags. It seems like you can have multiple `<tbody>` within one `<table>`.

But then we'd need to make sure that if you already specify a `<tbody>`, we don't go tbody > tbody, because that's illegal.

**Comment by kevindeyne** [comment]
I think you can ignore my encoding branch.

I tried the above, conditionally swapping `div` with `tbody` in case of a `table` parent, as well as removing internally a wrapping `tbody`.

I've updated that in [bug/iteration-table](https://github.com/medusa-ui/medusa/tree/bug/iteration-table). At first glance, looks to work better?

**Comment by mhaupt** [comment]
Thank you for looking into this!

The branch looks much better, however there is at least one test still failing:
```
org.opentest4j.AssertionFailedError: expected: <0> but was: <4>
	at com.sample.medusa.bug.TableIterationIntegrationTest.tableDOMChanges(TableIterationIntegrationTest.java:86)
```

It seems the table may not be cleansed of all elements properly when the "clear" button is clicked.

**Comment by dirkdeyne** [comment]
There was still a small issue in handling an `IterationTag`.
Fixed now, and all tests should pass.

**Comment by mhaupt** [comment]
Indeed, thank you!

**Comment by kevindeyne** [comment]
@dirkdeyne FYI - I added a fix for the mistake we spotted on Friday. Instead of doing all the parent determination on the foreaches, I'm doing it properly on the foreach element.

**Comment by mhaupt** [comment]
Thanks!
