### ISSUE TITLE
Rewrite: form submit action

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#248]
Will need a custom Thymeleaf tag that triggers on a form submit.

- [x] Actual form submits have to be cancelled
- [x] The form must become available as parameter to the controller method as a Map<String, Object> or map onto a POJO.
- [ ] (Optional) A common pattern is to disable a button after button press until the message is resolved, to prevent double-clicking to fire an event twice. Perhaps this should be an option with this default on?
- [ ] (Optional) Validation of forms is a very common pattern. Is there a way we can make this easier in Medusa?

**Comment by kevindeyne** [comment]
Implemented the basics of form tag: https://medusa-showcase.herokuapp.com/detail/form-submit
Would still need to think about validation/button disabling

**Comment by kevindeyne** [comment]
For Validation, consider integration with https://github.com/making/yavi which seems to have traction on github

**Comment by dirkdeyne** [comment]
One thing I noticed: when adding `Session` in the submit method, it needs to be the last argument of that method.
_Note_: for other calls like `m:click` the position of the session argument can be first or last...

**Comment by dirkdeyne** [comment]
Failed to use multi-select in form ref: [sample in medusa-ui path: '/multi-select'](https://github.com/medusa-ui/medusa/commit/6a361602fe0845c023abc5902cc2e76510359889)

**Comment by kevindeyne** [comment]
Any easier now? I've made it resolve to a dynamic List instead of an Object[] now.

So you should be able to do something like:
`Map<String, List<String>> form`  if you only expect multi lists to show up in the form.

I'm not really sure how I could make a map that does both single values and multi values easier otherwise. That's kind of what the POJO mapping is for.

**Comment by dirkdeyne** [comment]
The problem is not `Object` versus `String`, but `Object` versus `Object[]` (or `String` versus `String[]`)

The multi-select has no problems when multiple options are selected, but occurs when only a **single option** is selected.
One would expect an Array with one Object, but instead, the selected option **is** an Object.

When using a map, you can use the workaround like in the above [example](https://github.com/medusa-ui/medusa/issues/248#issuecomment-1253951865).
When using a POJO there is no workaround, you get an error: 

> MismatchedInputException: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value

_Ref_: [multi-select](http://localhost:8080/multi-select)  in `medusa-ui` Sample application

**Comment by kevindeyne** [comment]
Applied JS fix as discussed, maybe this will solve the problem?

**Comment by dirkdeyne** [comment]
Select multiple works fine now! 👍
Included detection for input fields with an identical name #326 
These too must send data as an Array.

**Comment by dirkdeyne** [comment]
For now only look at checkboxes with identical names
