### ISSUE TITLE
IdentifierGenerator is not working ideally

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/medusa#8]
Right now, identifierGenerator works like this:

https://github.com/medusa-ui/medusa/blob/bc39079f701396439deac7b9309209dba5970c2e/src/main/java/io/getmedusa/medusa/core/util/IdentifierGenerator.java#L5-L16

And that's potentially a little dangerous. 

Imagine scenario:
You have two iterations on the same content, as such:

```
[$foreach $items-bought]
    <p>Medusa</p>
[$end]

[$foreach $items-bought]
    <p>Medusa</p>
[$end]
```

The ID would only hash the content, so it would generate the same for both iterations - causing confusion and invalid HTML (id needs to be unique).

But at the same time I need to make sure that no matter how many refreshes you do, it always generates the same ID (otherwise the ConditionalRegistry or IterationRegistry does not have the right reference -> you get a situation where things work until you refresh).

Not sure what the best solution for this is.

**Comment by dirkdeyne** [comment]
Possible fix in PR #40

Changes:
- [`IterationTag`](https://github.com/medusa-ui/medusa/blob/334f8bfe37a01b1cfad597a0ed28915b4c6ae0c7/medusa-ui/src/main/java/io/getmedusa/medusa/core/injector/tag/IterationTag.java#L30): use `m-id` instead of `id` for the template
- [`websocket.js`](https://github.com/medusa-ui/medusa/blob/334f8bfe37a01b1cfad597a0ed28915b4c6ae0c7/medusa-ui/src/main/resources/websocket.js#L141): loop through each template-element with an `m-id`

example page: http://localhost:8080/history
